Add rofi support
moverest/sway-interactive-screenshot pull request #20
Opened 2024-04-14 12:57 UTC by Ciubix8513

Fix for #16

Rofi can be enable in the config, there you can also specify the rofi theme

2024-04-14 20:12 UTC, moverest commented
Thank you for your PR @Ciubix8513, I like the idea of using `rofi` instead of `fuzzel` for users that want this.

I think we could improve the implementation here with a bit of polymorphism &mdash; the idea being that only on the initialisation stage should we care about the implementation of the `ask()` function.

In the configuration we could have the `[ask]` which would look like this if we want to use `rofi`:

```toml
[ask]
command = "rofi"
additional_args = ["-theme", "Arc"]
```

But would default to:

```toml
[ask]
command = "fuzzel"
```

Which would make use of `fuzzel` by default.

Then we'd have in the scrip two `ask_*` functions: `ask_rofi` and `ask_fuzzel` and a `ask` variable which will point to the implementation with the configuration the used set. They would have the same base arguments.

```python

def ask_fuzzel(
    choices: List[Any],
    *,
    prompt: Optional[str] = None,
    lines: Optional[int] = None,
    index: bool = False,
    additional_args: List[str] = [],
) -> Union[int, str, None]:
   ...

def ask_rofi(
    choices: List[Any],
    *,
    prompt: Optional[str] = None,
    lines: Optional[int] = None,
    index: bool = False,
    additional_args: List[str] = [],
) -> Union[int, str, None]:
   ...

ASK_FNS = {
    "rofi": ask_rofi,
    "fuzzel": ask_fuzzel,
}

ask = ask_fuzzel
```

In the `main()` function, we'd look at the configuration and set the `ask` global variable:

```python
ask = partial(
    ASK_FNS[config.get("ask", "command"),
    additional_args=config.get("ask", "additional_args")
)
```

This way, `ask()` is called the same way whatever the implementation is &mdash; that is using `fuzzel` or `rofi`. Also, I'll make more sense to have a `additional_args` in the configuration which would be passed to the program and could contain the theme (and whatever the user wants) instead of just handling the theme.

2024-04-14 21:37 UTC, Ciubix8513 commented
Yea, that sounds like a good idea

2024-04-15 19:03 UTC, moverest requested changes
This looks nice. I've made a few comments. Once there are addressed, I'll merge this. :slightly_smiling_face:

2024-04-15 19:03 UTC, moverest commented on sway-interactive-screenshot
> +    print(additional_args)
You probably didn't intend to include this.

```suggestion
```

2024-04-15 19:03 UTC, moverest commented on sway-interactive-screenshot
> +    if additional_args is not None:
Nit.: The condition also works if the list is empty, so this can be shorten a bit.

```suggestion
    if additional_args:
```

Here, `bool(additional_args)` is true if it's not `None` nor an empty list.

2024-04-15 19:03 UTC, moverest commented on sway-interactive-screenshot
> +        ask =  partial(
For this to work, `global ask` needs to be used before the assignment otherwise a local copy of `ask` is made inside the scope of the function.

2024-04-15 19:03 UTC, moverest commented on sway-interactive-screenshot
> +
Nit.: `choice_idx` is not used before so this is not necessary.

```suggestion
```

2024-04-15 19:03 UTC, moverest commented on sway-interactive-screenshot
> +                        "args" : config_type_validator(List),
It would make sense to add a `config_list_validator()`:

```python
def config_list_validator(*types: Type) -> CONFIG_VALIDATOR:
    def validate(path: str, value: Any) -> Iterator[ValidationError]:
        if not isinstance(value, list):
            yield ValidationError(path, f"Expected a list")
            return

        for i, element in enumerate(value):
            if not isinstance(element, types):
                yield ValidationError(
                    f"{path}[{i}]", f"Type {type(value)} is not one of {', '.join(types)}."
                )

    return validate
```

This line would then become:

```suggestion
                        "args" : config_list_validator(str),
```

2024-04-15 19:55 UTC, Ciubix8513 commented
I think i fixed everything

2024-04-16 13:52 UTC, moverest approved these changes

2024-04-16 13:53 UTC, merged

2024-04-16 13:54 UTC, moverest commented
Awesome! It's merged now, thank you for your contribution @Ciubix8513.